set -g status-style "fg=#E5DDD0,bg=#090807"
set -g status-left-style "fg=#E5DDD0,bg=#3A3632,bold"
set -g status-right-style "fg=#E5DDD0,bg=#181614"
set -g window-status-style "fg=#5A5248,bg=#090807"
set -g window-status-current-style "fg=#090807,bg=#FF4719,bold"
set -g window-status-activity-style "fg=#E8A030,bg=#090807"
set -g window-status-bell-style "fg=#FFFFFF,bg=#D71921,bold"
set -g pane-border-style "fg=#3A3632"
set -g pane-active-border-style "fg=#FF4719"
set -g message-style "fg=#E5DDD0,bg=#090807"
set -g message-command-style "fg=#E5DDD0,bg=#3A3632"
set -g mode-style "fg=#090807,bg=#E8A030"
set -g clock-mode-colour "#E8A030"
set -g popup-style "fg=#E5DDD0,bg=#090807"
set -g popup-border-style "fg=#3A3632"
set -g display-panes-colour "#E8A030"
set -g display-panes-active-colour "#FF4719"
